#!/usr/bin/env node

var request = require('request'),
	status_codes = require('http').STATUS_CODES,
	format = require('util').format,
	netrc = require('node-netrc'),
	auth = netrc('api.github.com') || {password: process.env.GH_TOKEN},
	keyword = process.argv[2],
	url = format('https://api.github.com/search/repositories?access_token=%s&q=%s+language%3Ajavascript', auth.login, keyword),
	opts = {
		headers: {'User-Agent': 'duo-search'},
		url: url,
		json: true
	};

var req = request(opts, function (error, response, body) {
	if (error) {
		console.error('duo-search:', error, 'Are you connected to the internet?');
		return process.exit(1);
	}

	var code = response.statusCode;
	if (code !== 200) {
		console.error(format('duo-search: %s %s', code, status_codes[code]));
		return process.exit(1);
	}

	body.items.filter(function (i) {
		return i.private === false;
	}).forEach(function (i) {
		console.log(i.full_name + ':');
		console.log('  ' + i.description);
		console.log();
	});
});
